sudo: required
language: generic
dist: bionic

install:
    - git clone --depth 1 https://github.com/google/googletest.git -b release-1.10.0
    - cd googletest        # Main directory of the cloned repository.
    - mkdir build          # Create a directory to hold the build output.
    - cd build
    - cmake ..             # Generate native build scripts for GoogleTest.
    - make
    - sudo make install
    - cd ../../
    - sudo apt update
    - sudo apt install valgrind lcov gcovr




before_script:
    - mkdir -p Release/
    - mkdir -p Debug/
    - cd Release
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - cd ../Debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make

script:
    - ./ManagerUnitTests
    - cd ../Release
    - valgrind --error-exitcode=1 --leak-check=full ./ManagerUnitTests
    - cd ../
#    - ./check_coverage.sh
